services:
  - type: web
    name: hustle-backend
    env: node
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        value: hustle_executive
      - key: PORT
        value: 3001 